const PDFDocument = require('pdfkit')

function generateReceipt(payment, tenant, unit, property, landlord) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 })
    const buffers = []

    doc.on('data', buffers.push.bind(buffers))
    doc.on('end', () => resolve(Buffer.concat(buffers)))
    doc.on('error', reject)

    // Header
    doc.fontSize(24).font('Helvetica-Bold').text('Stablee', 50, 50)
    doc.fontSize(10).font('Helvetica').fillColor('#666666')
      .text('Rent Management Platform', 50, 80)

    // Receipt title
    doc.moveTo(50, 110).lineTo(550, 110).stroke('#eeeeee')
    doc.fontSize(18).font('Helvetica-Bold').fillColor('#000000')
      .text('Payment Receipt', 50, 125)

    // Receipt details
    doc.fontSize(10).font('Helvetica').fillColor('#666666')
      .text(`Receipt ID: ${payment.id.slice(0, 8).toUpperCase()}`, 50, 155)
      .text(`Date: ${payment.payment_date}`, 50, 170)
      .text(`Generated: ${new Date().toLocaleDateString('en-NG')}`, 50, 185)

    // Divider
    doc.moveTo(50, 210).lineTo(550, 210).stroke('#eeeeee')

    // Property & Tenant info
    doc.fontSize(11).font('Helvetica-Bold').fillColor('#000000')
      .text('Tenant Details', 50, 225)

    doc.fontSize(10).font('Helvetica').fillColor('#333333')
      .text(`Name: ${tenant.full_name}`, 50, 245)
      .text(`Phone: ${tenant.phone}`, 50, 260)
      .text(`Property: ${property.name}`, 50, 275)
      .text(`Unit: ${unit.unit_number}`, 50, 290)
      .text(`Address: ${property.address}, ${property.city}`, 50, 305)

    // Divider
    doc.moveTo(50, 330).lineTo(550, 330).stroke('#eeeeee')

    // Payment info
    doc.fontSize(11).font('Helvetica-Bold').fillColor('#000000')
      .text('Payment Details', 50, 345)

    doc.fontSize(10).font('Helvetica').fillColor('#333333')
      .text(`Payment Method: ${payment.method.charAt(0).toUpperCase() + payment.method.slice(1)}`, 50, 365)
      .text(`Payment Cycle: ${unit.payment_cycle.charAt(0).toUpperCase() + unit.payment_cycle.slice(1)}`, 50, 380)
      .text(`Status: Paid`, 50, 395)

    // Amount box
    doc.rect(50, 420, 500, 60).fill('#f0f7ff')
    doc.fontSize(12).font('Helvetica').fillColor('#666666')
      .text('Amount Paid', 70, 435)
    doc.fontSize(22).font('Helvetica-Bold').fillColor('#1a56db')
      .text(`NGN ${Number(payment.amount).toLocaleString()}`, 70, 453)

    // Footer
    doc.moveTo(50, 510).lineTo(550, 510).stroke('#eeeeee')
    doc.fontSize(9).font('Helvetica').fillColor('#999999')
      .text('This receipt was automatically generated by Stablee.', 50, 525, { align: 'center' })
      .text('For support, contact your landlord.', 50, 540, { align: 'center' })

    doc.end()
  })
}

module.exports = { generateReceipt }